### ISSUE TITLE
debugging boolean constraint

### ISSUE THREAD

**Issue by mayork** [hoburg/turbofan#1]
@bqpd what's the best way to find which constraint in `CFM_56_performance_components_setup.py` is a boolean? I've looked through it and didn't see it. I also tried to print the constraint inside `set.py` but that just resulted in `False` being printed out...

**Comment by bqpd** [comment]
hmm, I'll take a look...

**Comment by bqpd** [comment]
Line 133:

```python
TCS([self.combustor['eta_{B}'] * self.engineP['f'] * self.combustor['h_f'] + self.engineP['h_{t_3}'] >= 'h_{t_4}']),
```

should be 


```python
TCS(self.combustor['eta_{B}'] * self.engineP['f'] * self.combustor['h_f'] + self.engineP['h_{t_3}'] >= self.combustor['h_{t_4}']),
```

**Comment by bqpd** [comment]
I'm working on a gpkit patch that would have highlighted this line.

**Comment by mayork** [comment]
ah great thanks! I was not looking at the right thing

**Comment by bqpd** [comment]
I can't close this issue, btw, since this is your repository...
