### ISSUE TITLE
Mysterious Constraint Properties

### ISSUE THREAD

**Issue by mayork** [hoburg/turbofan#2]
@bqpd I've been attempting to debug the engine code and noticed a few interesting things. Using the file 'engine_Debug.py' i generated a list of all constraints that are different between the two files. It prints a lot of constraints but most are just inverses of each other. The file that works is `CFM_56_validation.py`, the file I'm debugging is `CFM_56_performance_components_setup.py`.

In `CFM_56_performance_components_setup.py` I replaced `u0` with `V` for the purposes of integrating with the rest of the D8 code where V is used for the free stream velocity. What I have noticed is that everywhere `V` appears in the performance and setup model there is a factor of 0.514 multiplying it. The constraint print out looks like

```
0.514*V*u_6**-1
0.514*V*u_6**-1
0.514*V*u_6**-1
0.514*V*u_6**-1
0.514*V*u_8**-1
0.514*V*u_8**-1
0.514*V*u_8**-1
0.514*V*u_8**-1



0.514*V*u_8**-1 + F_8*\alpha**-1*m_{core}**-1*u_8**-1
0.514*V*u_8**-1 + F_8*\alpha**-1*m_{core}**-1*u_8**-1
0.514*V*u_8**-1 + F_8*\alpha**-1*m_{core}**-1*u_8**-1
0.514*V*u_8**-1 + F_8*\alpha**-1*m_{core}**-1*u_8**-1

0.514*V*u_7**-1
0.514*V*u_7**-1
0.514*V*u_7**-1
0.514*V*u_7**-1

0.514*V*u_5**-1
0.514*V*u_5**-1
0.514*V*u_5**-1
0.514*V*u_5**-1



0.514*V*f*fp1**-1*u_6**-1 + 0.514*V*fp1**-1*u_6**-1 + 1.05*F_6*fp1**-1*m_{core}**-1*u_6**-1
0.514*V*f*fp1**-1*u_6**-1 + 0.514*V*fp1**-1*u_6**-1 + 1.05*F_6*fp1**-1*m_{core}**-1*u_6**-1
0.514*V*f*fp1**-1*u_6**-1 + 0.514*V*fp1**-1*u_6**-1 + 1.05*F_6*fp1**-1*m_{core}**-1*u_6**-1
0.514*V*f*fp1**-1*u_6**-1 + 0.514*V*fp1**-1*u_6**-1 + 1.05*F_6*fp1**-1*m_{core}**-1*u_6**-1
```

The file that works has the constraint 

`u_8 >= F_8*\alpha**-1*m_{core}**-1 + u_0`

while the non-working file has

```
 [0.514*V_Engine, TestState_(0,) + F_8_Engine, EnginePerformance, ThrustPerformance_(0,)*\alpha_Engine, EnginePerformance, ThrustPerformance_(0,)**-1*m_{core}_Engine, EnginePerformance, ThrustPerformance_(0,)**-1, 0.514*V_Engine, TestState_(1,) + F_8_Engine, EnginePerformance, ThrustPerformance_(1,)*\alpha_Engine, EnginePerformance, ThrustPerformance_(1,)**-1*m_{core}_Engine, EnginePerformance, ThrustPerformance_(1,)**-1] <= u_8
```

there's two weird things about the constraint above. First, the factor of .514. secondly, I don't understand why u8 isn't a vector because it's created inside of vectorized.

Do you have any thoughts on either discrepancy? I tried to track down this .514 but don't see where it's coming from.

**Comment by mayork** [comment]
update: I'm really stupid, the factor of .514 is a units conversion. I forgot that I `V` was kts and `u0` is m/s

the question about `u8` being a vector still stands

**Comment by bqpd** [comment]
`u_8` is probably still a vector; when you print an arrayconstraint, if one side is a VectorVariable it only prints the veckey, and as part of the table improvement we removed the`\vec{}` from veckey display.

**Comment by mayork** [comment]
i believe you were correct
