### ISSUE TITLE
can't import package inside d8 folder

### ISSUE THREAD

**Issue by mayork** [hoburg/turbofan#6]
@bqpd i tried to make this an installable package and can successfully run a pip install but cannot import the turbofan package inside the D8 folder. I tried doing pip install with the -H command as well and that didn't help. What am I missing?

**Comment by bqpd** [comment]
Michael has more direct experience with this than me, but I'll try to stop
by y'all's office this afternoon!

**Comment by mayork** [comment]
I an the init a level too high, issue resolved
